### ISSUE TITLE
Could not find artifact com.typesafe.netty:netty-http-pipelining:jar:1.1.2

### ISSUE THREAD

**Issue by straumat** [halkeye/codacy-maven-plugin#7]
Since some days, i get this message using your plugin : 

[ERROR] Failed to execute goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage (default-cli) on project blockchain2graph: Execution default-cli of goal com.gavinmogan:codacy-maven-plugin:1.0.3:coverage failed: Plugin com.gavinmogan:codacy-maven-plugin:1.0.3 or one of its dependencies could not be resolved: Could not find artifact com.typesafe.netty:netty-http-pipelining:jar:1.1.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

http://mvnrepository.com/artifact/com.typesafe.netty/netty-http-pipelining

**Comment by straumat** [comment]
I use mvn com.gavinmogan:codacy-maven-plugin:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml -DprojectToken=$CODACY_PROJECT_TOKEN -DapiToken=$CODACY_PROJECT_TOKEN in a travis script

**Comment by halkeye** [comment]
I'll take a look when I can. I don't really work on any java projects right
now. Do you have a travis log that fails? or what version of java/maven?

**Comment by straumat** [comment]
Thanks a lot. Logs are here : https://api.travis-ci.org/v3/job/351798323/log.txt
I did not change anything on java and maven and it works for months.
Maybe you just need to upgrade netty-http-pipelining:jar ?

**Comment by straumat** [comment]
I was in hurry. I had to find a solution and codacy now provides a method that works well with Travis : https://github.com/codacy/codacy-coverage-reporter#travis-ci Thanks a lot for ur usefull tool, i will use codacy tool now. Thanks again

**Comment by halkeye** [comment]
I tried a few times but was unable to reproduce it. i'm thinking it has something to do with the dependencies of the actual project
